apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongodb-secret
        volumeMounts:
          - name:  mongo-data
            mountPath:  /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: host-pvc