apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb
spec:
  selector:
    matchLabels:
      type: local
    storageClassName: manual
    accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem