apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: dbport
  clusterIP: None

## mongodb-statefulset-0.mongodb-svc.mongodb.svc.cluster.local (POD)
## mongodb-svc.mongodb.svc.cluster.local (SVC)git add