apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.8
        resources:
          limits:
            memory: "256Mi"
            cpu: "90m"
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongodb-secret
        volumeMounts:
          - name:  pvc-mongodb
            mountPath:  /data/db
  volumeClaimTemplates:
  - metadata:
      name: pvc-mongodb
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
          requests:
            storage: 2Gi
      storageClassName: do-block-storage